### ISSUE TITLE
This action expects an exact match, including spaces and new lines. Maybe it shouldn't.

### ISSUE THREAD

**Issue by ArielMAJ** [GuillaumeFalourd/test-cli-commands-action#4]
Hey, I've been trying out this action for the past couple days. It's been everything I've been wanting and it's been really useful and helpful to me. But there's something something I've realized:
- It expects the input and output to be an exact match, including spaces at the end of each line and new line characters at the end of the output. **It would probably be a lot better if both were ignored** (or if there was **a boolean option to start ignoring them**).

I had about a hundred "test cases" already written in which I started using this action for testing automatically. I had tested my code with all those test cases in another platform and it all worked well. But a lot of them were failing in GH, some for seemingly no reason. 
Then, somehow, I started realizing that some of my code had "trailing spaces" at the end of each printed line, some of it didn't have a new line character at the end of the last printf etc. It was about the same for the test files: some had "trailing spaces" at the end of each line, while most didn't, most of them didn't have new lines at the end of the file (I later added to them all for consistency), etc.

There were a lot of these small things both in the printing behavior of my code and the files with the expected output. And that's where most of the failed tests happened.

Ex.:
```
// Originial printing function. This doesn't work if the test files have no space at the end of each line.
void print_matrix(float **mat, int rows, int columns)
{
	for (int row = 0; row < rows; row++)
	{
		for (int column = 0; column < columns; column++)
			printf("%.1f ", mat[row][column]);
		printf("\n");
	}
}

// Changes necessary for this function to work specifically with this GH action.
void print_matrix(float **mat, int rows, int columns)
{
	for (int row = 0; row < rows; row++)
	{
		for (int column = 0; column < columns; column++)
		{
			printf("%.1f", mat[row][column]);
			if (column != columns - 1)
				printf(" ")
		}
		printf("\n");
	}
}
```

Not ignoring spaces (both their existence and/or absence) at the end of each line makes this action a lot stricter and harder to use both for who's writing the tests and for who's writing the code. The same goes for the new lines at the end of the file. Ignoring both of these things would make this tool quite a bit more flexible (if that's not too hard ofc. It certainly is above my skillset).

Cheers!

**Comment by GuillaumeFalourd** [comment]
Hi @ArielMAJ , thank you for opening this issue and for the feedback! 🚀 

This is something I worked on initially when building this action, and I had some issues with the trailing and new line syntax as it was working differently on DOS and Unix runners, and I wanted the action to work on all OS runners (that's the reason why I ended up adding the `npm strip-ansi` tool to the workflow, as well as the `diff --strip-trailing-cr` flag).

It would be great to have the possibility to add this feature, I just wonder how I could achieve this using the shell `bash` alone (to maintain the action compatibility on all os runner). Do you have any idea / suggestion regarding how it would be possible to achieve this?

**Comment by ArielMAJ** [comment]
It's amazing to know you've already ran into all those other issues so long ago trying to deal with a thing I just thought up and suggested. 

I don't know much bash programming at all and I really have no idea how to start understanding your bash code nor coming up with a solution to this problem in that language. Your idea of sending what's printed to stdout to a txt file and comparing it to a base test txt file was kinda mind blowing for me though. It led me to learning how to use the bash commands "<" and ">", which opened up a quite easy and "straightforward" way for me to code up my own solution in python:

1. Using "os.system(command_line + ' > output.txt')" it's possible to run the user command from within the python script and save the output to a txt file (I just realized it doesn't actually need to be in the python script, but being like that makes it easier to run those tests locally);
2. After that it's easy and simple python code to strip trailing spaces and new lines from each line and comparing them.

I ended up going overboard and made it so this python script I wrote goes through all subfolders and all tests in those subfolders of a given folder (automatically through GH actions, but I also can easily run it locally).

I can't really say it for sure, but (from my tests on a private repository) i believe it should work the same in Ubuntu, MacOS and Windows (I think there were some problems printing emojis in Windows, but we could mix bash in there to circumvent it and make the output pretty). 

- Would you be interested in trying to change your Action so it can process the text using Python?
- What were the problems you ran through with specific OSs btw? (please don't say it has to do with emojis lol)

**Comment by GuillaumeFalourd** [comment]
```Would you be interested in trying to change your Action so it can process the text using Python?```
Sure, if we can maintain the current behavior and compatibility on all OS, and at the same time add new features to improve the action, I'm totally opened to it.

```What were the problems you ran through with specific OSs btw?```
It was basically related to the kernel. Using those Bash commands to create a .txt file generated the same file output when I looked at it on a UI for DOS (windows) or Unix(Linux / MacOS), but as the file was created using different OS, the file structure was different (for example: to break a line on Unix you use `\n`, but with DOS it use `\r\n`). You can't see it when looking at the .txt file, but the `diff` command identifies the difference.

* * *

If you're interested in contributing with your python script, I can create a new branch with the structure prepared for python, and let you insert your code on a python file for us to test it.

**Comment by ArielMAJ** [comment]
`for example: to break a line on Unix you use \n, but with DOS it use \r\n`
That's interesting! I didn't even know this \r character existed until now, but handling it shouldn't be a problem at all in python either way.

`If you're interested in contributing with your python script, I can create a new branch with the structure prepared for python, and let you insert your code on a python file for us to test it.`
Sure! I'd like to try working on it a bit.

**Comment by GuillaumeFalourd** [comment]
Ok 😄 

I created a branch [v3](https://github.com/GuillaumeFalourd/assert-command-line-output/tree/v3) from `main`, where I updated the action to use an `assert.py` file. I already set the action inputs parameters to manipulate them in the file.

If you update this file in a fork and open an PR, it should trigger the github actions workflows for tests 👍🏼

**Comment by ArielMAJ** [comment]
I was playing around with C a little bit and ended up reimplementing everything there. Should I pull request it into the same v3 branch as well?

**Comment by GuillaumeFalourd** [comment]
Hi @ArielMAJ
I merged your v3 branch into mine to make some tests.
Why would you like to migrate to C? Is there any advantage compared to Python?

**Comment by ArielMAJ** [comment]
```Is there any advantage compared to Python?```
Tbh, not really.

I was trying to implement a way to read whole group of folders and do assertions with many input&output files. My implementation of that ended up being quite slow. As I'm currently studying C, I felt inclined to check how faster it would be if done in that language.

In reality reading a group of folders was quite fast with python in my first try. It only became slow because I later tried to come up with weird premisses that led to lots of looping.

**Comment by GuillaumeFalourd** [comment]
Let's keep it in Python then. I believe that as it's a wider used language, it will allow more people to contribute to the repository if they identify possible enhancements 😄
